version: '3.9'

services:
  redis:
    image: redis:7
    container_name: ${REDIS_CONT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${FLASK_CONT}
    env_file:
      - .env
    ports:
      - '${FLASK_PORT}:${FLASK_PORT}'
    depends_on:
      - redis
    command: flask run --host=${FLASK_HOST} --port=${FLASK_PORT}

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CELERY_CONT}
    env_file:
      - .env
    depends_on:
      - redis
      - web
    command: celery -A ${CELERY_APP} worker --loglevel=info --autoscale=${CELERY_AUTOSCALE}
