services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_server
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SQLALCHEMY_DATABASE_URI=sqlite:///models.db
      - OPENAI_API_KEY=${OPENAI_API_KEY} # <-- pass host env var
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rq_worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SQLALCHEMY_DATABASE_URI=sqlite:///models.db
      - OPENAI_API_KEY=${OPENAI_API_KEY} # <-- pass host env var
    depends_on:
      - redis
      - web
    command: ['python', 'server/jobs/consumer.py']
